### ISSUE TITLE
代码训练存在的问题

### ISSUE THREAD

**Issue by zqwang21** [ming71/CFC-Net#10]
验证时候遇到“RuntimeError:Given input size :(256*56*52).Calculated output size:(256*1*0).Output size is too small”问题，请问怎么解决？是什么问题

**Comment by ming71** [comment]
我没遇到过这个问题。根据描述来看可能是输入尺寸设置过小导致某处的pooling操作无法进行



在 2022-01-08 20:35:44，"zqwang21" ***@***.***> 写道：

验证时候遇到“RuntimeError:Given input size :(2565652).Calculated output size:(25610).Output size is too small”问题，请问怎么解决？是什么问题

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zqwang21** [comment]
学长您好，我把出错的图片进行了删除操作，然后成功训练了，但在测试的时候出现了这种错误，想问一下学长是什么原因？谢谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ming71/CFC-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月10日(星期一) 上午9:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ming71/CFC-Net] 代码训练存在的问题 (Issue #10)





 我没遇到过这个问题。根据描述来看可能是输入尺寸设置过小导致某处的pooling操作无法进行
 
 
 
 在 2022-01-08 20:35:44，"zqwang21" ***@***.***&gt; 写道：
 
 验证时候遇到“RuntimeError:Given input size :(2565652).Calculated output size:(25610).Output size is too small”问题，请问怎么解决？是什么问题
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ming71** [comment]
你删除的什么图片？

**Comment by zqwang21** [comment]
您好，我删除了验证集里面的100001042和100001047这两张图片，如果不删除，代码训练验证的时候会出现错误




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ming71/CFC-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月11日(星期二) 下午3:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ming71/CFC-Net] 代码训练存在的问题 (Issue #10)





 
你删除的什么图片？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ming71** [comment]
不好意思，我没有遇到过这个问题。现在删除后可以跑起来了吗？

**Comment by zqwang21** [comment]
是的，可以跑起来，但测试的时候会报错，错误如图所示：想问一下是什么原因



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "ming71/CFC-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月12日(星期三) 上午10:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ming71/CFC-Net] 代码训练存在的问题 (Issue #10)





 
不好意思，我没有遇到过这个问题。现在删除后可以跑起来了吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by IsenLwww** [comment]
> 验证时候遇到“RuntimeError:Given input size :(256_56_52).Calculated output size:(256_1_0).Output size is too small”问题，请问怎么解决？是什么问题

你好，请问你成功解决了这个问题了吗
