### ISSUE TITLE
您好，请问您是如何可视化目标检测特征

### ISSUE THREAD

**Issue by li-chen-ai** [ming71/CFC-Net#13]
您好，请问您是如何可视化特征的，像论文中的那样，在代码的哪个部分呢，想学习一下

**Comment by ming71** [comment]
repo中没有给出可视化代码，对多尺度特征作gap然后归一处理即可

**Comment by li-chen-ai** [comment]
收到，感谢您的回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ming71/CFC-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月6日(星期一) 晚上9:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ming71/CFC-Net] 您好，请问您是如何可视化目标检测特征 (Issue #13)





 
repo中没有给出可视化代码，对多尺度特征作gap然后归一处理即可
